### ISSUE TITLE
Radio icon disappears after replace

### ISSUE THREAD

**Issue by Clandaries** [hvdwolf/Joying-RootAssistant#1]
Hello,

when i use the install.bat and reboot my device, the appicon is gone and i cant use the radio app anymore.

Someone knows a sulution for this? 

Greetings

**Comment by hvdwolf** [comment]
Are you on 5.1.1 or already on 6.0.1?

If you are on 6.0.1 you have to know that this can be an issue on many occasions when replacing apks. Sometimes it works, sometimes it doesn't, like in your case.

I just split up my RadioMods in a 5.1.1 and a 6.0.1 section. I was working on that when your issue was posted.
Both the 5.1.1 and 6.0.1 also contain the standard default radio app under JOYING_DEFAULT.
I do not know whether you use a 5.1.1 mod on 6.0.1 but I simply don't know whether that will work at all.

Anyway:
- reboot your unit
- install the default radio app
- reboot your unit
(and you might even have to repeat that another time given the strange behavior of the new 6.0.1)

**Comment by Clandaries** [comment]
Ah, ok.

I am on 6.0.1.

So i need your 6.0.1 apk.

Where to get it?

Thank you :)

**Comment by Clandaries** [comment]
Found it.

Thank you.

Will test.
