### ISSUE TITLE
error: more than one device/emulator

### ISSUE THREAD

**Issue by icarusza** [hvdwolf/Joying-RootAssistant#9]
Hello!

I am a total noob herre but have followed the instructions to root my device. 

It appeared to work once but after it finished and i rebooted the device. Nothing happend so I tryed again.. and I get this..

C:\Superuser>install.bat 172.18.91.75
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
connected to 172.18.91.75:5555
error: more than one device/emulator
already connected to 172.18.91.75:5555
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
error: more than one device/emulator
Reboot your Head Unit NOW!

**Comment by hvdwolf** [comment]
Sorry, but questions are not answered here. In this case also because I have no idea what causes this, but sometimes it is just plain stupid to reboot the unit, reboot your pc/laptop, and try again.

Everything is supported via the XDA forum. There are several threads dealing with this.
The thread https://forum.xda-developers.com/android-auto/android-head-units/joying-extra-tools-apk-apk-to-help-t3628200 might be the best. That one is also from me, but is used also for rooting questions. Maybe there are other users having rooted their unit who also encountered this error.

**Comment by icarusza** [comment]
Thanks! A reboot sorted it out. (if any one is also having this problem.)
rebooted head unit and it was rooted this time!
woop woop!

C:\Superuser>install.bat 172.18.91.75
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
connected to 172.18.91.75:5555
restarting adbd as root
connected to 172.18.91.75:5555
492 KB/s (602704 bytes in 1.195s)
63 KB/s (979 bytes in 0.015s)
620 KB/s (1005729 bytes in 1.582s)
11 KB/s (145 bytes in 0.012s)
Reboot your Head Unit NOW!
